import { getCookieByKey } from "../cookies";

const country = [
  { country: "af", apple: "Yes", android: "N/A", huawei: "N/A" },
  { country: "ax", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "al", apple: "No", android: "Yes", huawei: "No" },
  { country: "dz", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "as", apple: "N/A", android: "No", huawei: "N/A" },
  { country: "ad", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "ao", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ai", apple: "Yes", android: "N/A", huawei: "Yes" },
  { country: "aq", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "ag", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "ar", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "am", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "aw", apple: "N/A", android: "Yes", huawei: "Yes" },
  { country: "au", apple: "No", android: "No", huawei: "No" },
  { country: "at", apple: "No", android: "Yes", huawei: "No" },
  { country: "az", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "bs", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "bh", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "bd", apple: "N/A", android: "Yes", huawei: "No" },
  { country: "bb", apple: "Yes", android: "N/A", huawei: "Yes" },
  { country: "by", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "be", apple: "No", android: "Yes", huawei: "No" },
  { country: "bz", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "bj", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "bm", apple: "Yes", android: "Yes", huawei: "N/A" },
  { country: "bt", apple: "Yes", android: "N/A", huawei: "N/A" },
  { country: "bo", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ba", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "bw", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "bv", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "br", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "io", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "bn", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "bg", apple: "No", android: "Yes", huawei: "No" },
  { country: "bf", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "bi", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "kh", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "cm", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ca", apple: "No", android: "No", huawei: "No" },
  { country: "cv", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "bq", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "ky", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "cf", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "td", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "cl", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "cn", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "cx", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "cc", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "co", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "km", apple: "N/A", android: "Yes", huawei: "N/A" },
  { country: "cg", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "cd", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "ck", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "cr", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "ci", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "hr", apple: "No", android: "Yes", huawei: "No" },
  { country: "cu", apple: "N/A", android: "Yes", huawei: "N/A" },
  { country: "cw", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "cy", apple: "No", android: "Yes", huawei: "No" },
  { country: "cz", apple: "No", android: "Yes", huawei: "No" },
  { country: "dk", apple: "No", android: "Yes", huawei: "No" },
  { country: "dj", apple: "N/A", android: "Yes", huawei: "No" },
  { country: "dm", apple: "Yes", android: "Yes", huawei: "N/A" },
  { country: "do", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "ec", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "eg", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "sv", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "gq", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "er", apple: "N/A", android: "Yes", huawei: "No" },
  { country: "ee", apple: "No", android: "Yes", huawei: "No" },
  { country: "et", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "fk", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "fo", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "fj", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "fi", apple: "No", android: "Yes", huawei: "No" },
  { country: "fr", apple: "No", android: "Yes", huawei: "No" },
  { country: "gf", apple: "N/A", android: "N/A", huawei: "Yes" },
  { country: "pf", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "tf", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "ga", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "gm", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ge", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "de", apple: "No", android: "Yes", huawei: "No" },
  { country: "gh", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "gi", apple: "N/A", android: "Yes", huawei: "No" },
  { country: "gr", apple: "No", android: "Yes", huawei: "No" },
  { country: "gl", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "gd", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "gp", apple: "N/A", android: "N/A", huawei: "Yes" },
  { country: "gu", apple: "N/A", android: "No", huawei: "N/A" },
  { country: "gt", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "gg", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "gn", apple: "N/A", android: "Yes", huawei: "No" },
  { country: "gw", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "gy", apple: "Yes", android: "N/A", huawei: "Yes" },
  { country: "ht", apple: "N/A", android: "Yes", huawei: "Yes" },
  { country: "hm", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "va", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "hn", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "hk", apple: "No", android: "No", huawei: "Yes" },
  { country: "hu", apple: "No", android: "Yes", huawei: "No" },
  { country: "is", apple: "No", android: "Yes", huawei: "No" },
  { country: "in", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "id", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ir", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "iq", apple: "No", android: "Yes", huawei: "N/A" },
  { country: "ie", apple: "No", android: "Yes", huawei: "No" },
  { country: "im", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "il", apple: "No", android: "Yes", huawei: "No" },
  { country: "it", apple: "No", android: "Yes", huawei: "No" },
  { country: "jm", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "jp", apple: "Yes", android: "No", huawei: "No" },
  { country: "je", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "jo", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "kz", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ke", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ki", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "kr", apple: "Yes", android: "Yes", huawei: "N/A" },
  { country: "kp", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "kw", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "kg", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "la", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "lv", apple: "No", android: "Yes", huawei: "No" },
  { country: "lb", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ls", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "lr", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ly", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "li", apple: "N/A", android: "Yes", huawei: "No" },
  { country: "lt", apple: "No", android: "Yes", huawei: "No" },
  { country: "lu", apple: "No", android: "Yes", huawei: "No" },
  { country: "mo", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "mk", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "mg", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "mw", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "my", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "mv", apple: "Yes", android: "Yes", huawei: "N/A" },
  { country: "ml", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "mt", apple: "No", android: "Yes", huawei: "No" },
  { country: "mh", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "mq", apple: "N/A", android: "N/A", huawei: "Yes" },
  { country: "mr", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "mu", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "yt", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "mx", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "fm", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "md", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "mc", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "mn", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "me", apple: "No", android: "N/A", huawei: "No" },
  { country: "ms", apple: "Yes", android: "N/A", huawei: "Yes" },
  { country: "ma", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "mz", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "mm", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "na", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "nr", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "np", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "nl", apple: "No", android: "Yes", huawei: "No" },
  { country: "nc", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "nz", apple: "No", android: "No", huawei: "No" },
  { country: "ni", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "ne", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ng", apple: "No", android: "No", huawei: "No" },
  { country: "nu", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "nf", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "mp", apple: "N/A", android: "No", huawei: "N/A" },
  { country: "no", apple: "No", android: "Yes", huawei: "No" },
  { country: "om", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "pk", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "pw", apple: "Yes", android: "No", huawei: "N/A" },
  { country: "ps", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "pa", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "pg", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "py", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "pe", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ph", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "pn", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "pl", apple: "No", android: "Yes", huawei: "No" },
  { country: "pt", apple: "No", android: "Yes", huawei: "No" },
  { country: "pr", apple: "N/A", android: "No", huawei: "Yes" },
  { country: "qa", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "re", apple: "N/A", android: "N/A", huawei: "No" },
  { country: "ro", apple: "No", android: "Yes", huawei: "No" },
  { country: "ru", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "rw", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "sh", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "kn", apple: "Yes", android: "N/A", huawei: "N/A" },
  { country: "lc", apple: "Yes", android: "N/A", huawei: "Yes" },
  { country: "pm", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "vc", apple: "Yes", android: "N/A", huawei: "Yes" },
  { country: "bl", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "mf", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "ws", apple: "N/A", android: "Yes", huawei: "No" },
  { country: "sm", apple: "N/A", android: "Yes", huawei: "No" },
  { country: "st", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "sa", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "sn", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "rs", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "sc", apple: "Yes", android: "Yes", huawei: "N/A" },
  { country: "sl", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "sg", apple: "No", android: "No", huawei: "No" },
  { country: "sx", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "sk", apple: "No", android: "Yes", huawei: "No" },
  { country: "si", apple: "No", android: "Yes", huawei: "No" },
  { country: "sb", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "so", apple: "N/A", android: "Yes", huawei: "N/A" },
  { country: "za", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "gs", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "ss", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "es", apple: "No", android: "Yes", huawei: "No" },
  { country: "lk", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "sd", apple: "N/A", android: "Yes", huawei: "N/A" },
  { country: "sr", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "sj", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "sz", apple: "Yes", android: "N/A", huawei: "No" },
  { country: "se", apple: "No", android: "Yes", huawei: "No" },
  { country: "ch", apple: "No", android: "Yes", huawei: "No" },
  { country: "sy", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "tw", apple: "No", android: "Yes", huawei: "No" },
  { country: "tj", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "tz", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "th", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "tl", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "tg", apple: "N/A", android: "Yes", huawei: "No" },
  { country: "tk", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "to", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "tt", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "tn", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "tr", apple: "No", android: "Yes", huawei: "No" },
  { country: "tm", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "tc", apple: "Yes", android: "N/A", huawei: "N/A" },
  { country: "tv", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "ug", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ua", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "ae", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "gb", apple: "No", android: "Yes", huawei: "No" },
  { country: "um", apple: "N/A", android: "No", huawei: "N/A" },
  { country: "us", apple: "No", android: "No", huawei: "N/A" },
  { country: "uy", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "uz", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "vu", apple: "No", android: "Yes", huawei: "N/A" },
  { country: "ve", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "vn", apple: "Yes", android: "Yes", huawei: "Yes" },
  { country: "vg", apple: "Yes", android: "N/A", huawei: "Yes" },
  { country: "vi", apple: "N/A", android: "No", huawei: "N/A" },
  { country: "wf", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "eh", apple: "N/A", android: "N/A", huawei: "N/A" },
  { country: "ye", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "zm", apple: "Yes", android: "Yes", huawei: "No" },
  { country: "zw", apple: "Yes", android: "Yes", huawei: "No" },
];
const clientsCountry = window.getClientCountry();

// Function to generate the text based on platform availability
function generateText(platforms) {
  const { apple, android, huawei } = platforms;

  if (apple === "Yes" && android === "Yes" && huawei === "Yes") {
    return "Android, iOS & Huawei";
  }

  if (apple === "Yes" && android === "Yes" && huawei !== "Yes") {
    return "Android, and iOS";
  }

  if (apple === "Yes" && huawei === "Yes" && android !== "Yes") {
    return "iOS, and Huawei";
  }

  if (android === "Yes" && apple !== "Yes" && huawei !== "Yes") {
    return "Android";
  }

  if (apple === "Yes" && huawei === "Yes" && android !== "Yes") {
    return "iOS, and Huawei";
  }

  if (apple === "Yes" && android !== "Yes" && huawei !== "Yes") {
    return "iOS";
  }
  if (apple !== "Yes" && android !== "Yes" && huawei === "Yes") {
    return "Huawei";
  }

  return "";
}

const clientPlatforms = country.find(
  (entry) => entry.country === clientsCountry
);
const generatedText = clientPlatforms ? generateText(clientPlatforms) : "";

const headingElement = document.getElementById("app-download-heading");
if (headingElement) {
  headingElement.innerText = generatedText;
}
