name: Daily CRON Job

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: |
          cd .github
          npm init -y
          npm install ws axios

      - name: Run script
        env:
          API_KEY: ${{ secrets.WEBFLOW_API_TOKEN }}
        working-directory: .github
        run: node dynamic-trading-specs.js
